const usageExamples=[["规则太多，AI 经常漏用或误用。","把测试和 API 开发规则整理清楚。"],["组件参数为了测试方便被放宽，业务代码出现无效兜底。","检查重命名回调是否真的需要可选。"],["旧 API 要分批迁移，每次都要重复交代同样要求。","每次迁移少量旧接口，检查通过后提 PR。"],["想改善代码质量，还没确定检测什么和先改哪里。","帮我确定要检测的问题、每轮任务和验收方式。"],["文字说明太长，看不清模块调用关系。","画出点击保存后经过哪些模块。"]];
const base='https://github.com/humanlayer/skills/blob/3c2629142c5d437428269b1b722b08c0b87f574d/plugins/';
const skills=[
{id:'improve-claude-md',name:'让规则在适当时刻生效',category:'规则整理',input:'现有 CLAUDE.md 与项目约定。',process:'保留基础背景；把领域规则按具体任务条件组织；去掉模糊、重复或应由工具检查的内容。',output:'精简后的 CLAUDE.md，包含条件化的规则块。',before:'所有任务都看到混在一起的测试、API、状态管理规则。',after:'当“修改 API 路由”时，明确提示路由位置、校验与错误格式。',boundary:'条件标签是提示词结构，没有强制执行能力；提升效果尚需对照评测。'},
{id:'narrow-react-prop-types',name:'让类型对应真实使用',category:'专项重构',input:'React 组件、所有生产调用以及相关测试与 Storybook。',process:'区分生产与辅助调用 → 判断必填、可选、可删除字段 → 收紧父子组件类型 → 调整测试并检查消费方。',output:'更严格的 Props、更少的无效兜底分支，以及依据真实调用的变更说明。',before:'onRename?: Handler；按钮始终出现，但使用 onRename?.()。',after:'生产路径全部提供回调时，改为必填 onRename 并直接调用。',boundary:'公开组件库需要额外核对外部 API 契约；缺少本地调用不是删除公共能力的充分证据。'},
{id:'build-iterated-agentic-loop',name:'把重复任务接入工作流',category:'自动化搭建',input:'已明确的重复任务、修改范围、验证命令、执行频率与 Agent。',process:'研究仓库 → 固化任务 Skill → 定制运行提示词、记忆和工作流 → 配置 PR 上限与 /iterate 反馈。',output:'仓库内 Skill、GitHub Actions YAML、记忆文件及可选反馈辅助脚本。',before:'每次都人工重复说明“找到问题、修改、验证、写 PR”。',after:'每轮读取固定规则与长期反馈，完成一个可审阅的小任务。',boundary:'这是工作流生成方法与模板；密钥、依赖、命令及任务验收均需定制并实测。'},
{id:'design-control-loop',name:'围绕质量目标设计闭环',category:'系统设计',input:'想改善的代码属性、现有检测工具与可接受的修改范围。',process:'确定目标 → 设计传感器与控制器 → 构建执行 Skill → 本地验证各组件 → 接入 CI、反馈与流量限制。',output:'可本地运行的检测与选择组件、执行 Skill、定时工作流和长期反馈；可选防退化检查。',before:'“让代码质量变好”缺乏可执行的测量和选择规则。',after:'扫描特定问题，每轮选择少量目标，验证改善后提交审阅。',boundary:'通用模板的 Sensor / Controller 保留 TODO；控制论是设计类比，不代表数学上的收敛保证。'},
{id:'show-me',name:'把复杂关系展示出来',category:'可视化解释',input:'当前需要理解的逻辑、调用关系、结构或方案变化。',process:'根据问题选择最小的解释形式：伪代码、调用树、文件树、diff、Mermaid 或聚焦的 HTML。',output:'紧贴问题的图解、代码结构草图或 HTML 解释页面。',before:'一长段文字描述模块调用和状态变化。',after:'用调用树看顺序，用 diff 看改动，用流程图看反馈关系。',boundary:'可视化由宿主 Agent 生成；Skill 本身没有独立渲染引擎，图中的事实仍需核实。'}
];
const list=document.querySelector('#skill-list');
const detail=document.querySelector('#skill-detail');
skills.forEach((skill,index)=>{const button=document.createElement('button');button.className='skill-tab';button.id=`tab-${skill.id}`;button.setAttribute('role','tab');button.setAttribute('aria-controls','skill-detail');button.innerHTML=`<span>0${index+1} / ${skill.id}</span><strong>${skill.name}</strong>`;button.addEventListener('click',()=>selectSkill(index));button.addEventListener('keydown',event=>{const keys=['ArrowDown','ArrowRight','ArrowUp','ArrowLeft','Home','End'];if(!keys.includes(event.key))return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?skills.length-1:(index+(event.key==='ArrowUp'||event.key==='ArrowLeft'?-1:1)+skills.length)%skills.length;selectSkill(next);list.children[next].focus();});list.append(button);});
function selectSkill(index){const skill=skills[index];[...list.children].forEach((button,i)=>{button.setAttribute('aria-selected',String(i===index));button.tabIndex=i===index?0:-1;});detail.setAttribute('aria-labelledby',`tab-${skill.id}`);detail.innerHTML=`<div class="eyebrow">${skill.category} / ${String(index+1).padStart(2,'0')}</div><h3>${skill.name}</h3><div class="example"><p><strong>什么时候用：</strong>${usageExamples[index][0]}</p><p><strong>你可以这样说：</strong>“${usageExamples[index][1]}”</p><p class="boundary">说明性示例；没有在此页面执行上游 Skill。</p></div><dl><dt>输入</dt><dd>${skill.input}</dd><dt>过程</dt><dd>${skill.process}</dd><dt>产物</dt><dd>${skill.output}</dd></dl><div class="example"><p><strong>示例 · 之前</strong> ${skill.before}</p><p><strong>示例 · 之后</strong> ${skill.after}</p></div><p class="boundary">边界：${skill.boundary}</p><a class="source" href="${base}${skill.id}/skills/${skill.id}/SKILL.md">阅读此 Skill 的固定版本源码 ↗</a>`;}
selectSkill(0);
const scenarios={research:{count:6,batch:1,steps:[['检测到 6 项资料问题','示例扫描发现：来源版本未记录、文档路径失效等。资料校验可复用现有脚本；版本变化检测需要另行扩展。'],['本轮只选择 1 个项目','控制器选择证据明确、影响范围小的研究文档。其他项目留到下一轮。'],['根据研究规则更新说明','模拟补充固定 commit、修复路径、写明证据。没有真实截图或已验证演示时保留空值。'],['独立检查通过（模拟）','模拟运行 projects.mjs check 与该子项目检查，并核对链接。通过验收后才准备 PR；尚未改变已合并的资料。'],['人工审阅并合并（模拟）','审阅者核对来源与结论。本例假设解决 1 项问题且没有新增问题，问题存量由 6 降到 5。'],['留下下一轮可用的反馈','把长期规则写入记忆文件，未来执行时再加载；一次运行日志不当作长期规则。']],memory:'缺少真实截图和已验证演示时保持空值；研究结论必须指向固定版本的证据。'},react:{count:8,batch:2,steps:[['发现 8 个候选组件','示例扫描发现可选回调与空数组兜底。候选信号不能直接证明类型可以收紧。'],['选择 2 个内部组件','先核对所有生产调用，选择调用关系明确的内部组件；公共导出暂留人工审阅。'],['收紧类型并更新辅助代码','模拟将始终提供的回调改为必填，清理无效兜底，并同步 Storybook 与测试。'],['消费方类型检查通过（模拟）','组件包和消费它的应用均通过示例验收。没有通过时应修复或停止，而非放宽类型掩盖问题。'],['人工确认并合并（模拟）','确认运行状态与类型契约一致。本例假设 2 个候选问题被解决且没有新增，存量由 8 降到 6。'],['记录适用范围','让未来运行记住公共接口边界；具体的测试输出只保留在当次记录中。']],memory:'公共组件导出需要核对外部 API 契约；不能仅凭仓库内未使用就删除能力。'},migration:{count:12,batch:3,steps:[['找到 12 处旧 API 调用','示例结构化搜索返回文件位置和旧调用模式；生成代码与供应商代码排除。'],['选择同一模块内 3 处','限制影响范围，采用仓库已经存在的新 API 用法作为正确模式。'],['按既有模式迁移','模拟更换 API 并处理返回值与错误语义，不顺便扩大重构范围。'],['目标测试通过（模拟）','模拟运行模块测试、构建及再次搜索；检查目标调用已消除，外部行为保持一致。'],['审阅合并（模拟）','本例假设迁移 3 处且没有新增旧调用，存量由 12 降到 9。真实项目还需考虑其他提交的影响。'],['沉淀有效的迁移规则','保留长期适用的排除范围与正确示例，下轮重新检测剩余问题。']],memory:'跳过生成文件与供应商目录；迁移沿用已有错误处理方式，一轮聚焦一个模块。'}};
let step=-1;
const selector=document.querySelector('#scenario'),gate=document.querySelector('#open-pr'),next=document.querySelector('#next'),output=document.querySelector('#run-output');
function render(){const scenario=scenarios[selector.value];document.querySelector('#metric').textContent=scenario.count-(step>=4?scenario.batch:0);document.querySelector('#metric-note').textContent=step>=4?'示例合并后；假设没有新增问题':'尚未合并修改';document.querySelectorAll('#stages li').forEach((li,index)=>{li.classList.toggle('done',index<step);li.classList.toggle('active',index===step);if(index===step)li.setAttribute('aria-current','step');else li.removeAttribute('aria-current');});const current=step<0?['等待开始一个维护周期','选择场景，逐步观察问题如何被检测、选择、修改与审阅。示例问题数量用于解释流程，不是本仓库的实际检测结果。']:scenario.steps[step];output.innerHTML=`<h3>${current[0]}</h3><p>${current[1]}</p>`;document.querySelector('#memory-text').textContent=step===5?scenario.memory:'尚无反馈。记忆是下次读取的文字规则，模型参数不会因此更新。';next.disabled=step===5;next.textContent=step<0?'开始检测 →':step===5?'本轮完成':`下一步：${['检测','选择','执行','验证','审阅','记忆'][step+1]} →`;gate.disabled=step>=0;}
next.addEventListener('click',()=>{if(step<0&&gate.checked){output.innerHTML='<h3>已有待审 PR，本轮暂停</h3><p>模拟默认定时触发：已有同标签 PR 时跳过，避免修改堆积。取消勾选后可继续。本次没有调用 Agent。</p>';return;}step=Math.min(step+1,5);render();});
function reset(){step=-1;render();}selector.addEventListener('change',reset);document.querySelector('#reset').addEventListener('click',()=>{gate.checked=false;reset();});gate.addEventListener('change',render);render();
