import {cases} from './cases.mjs';
const goals=[
 ['tea','我想推出一款茶产品','先看到产品长什么样，再决定怎么做。','产品效果图 / 包装方向提案','产品定位、茶品信息、容器照片或尺寸、希望传达的气质。','把“自然、安静、轻盈”等要求转成配色、主体、字体与包装视觉。','包装概念与产品效果图，用于内部选方向、向合作方说明想法。','确定方案后，补齐品牌标识、准确文案、包装刀模与印刷文件，再打样生产。','作者有包装效果示例；本项目未做茶产品生产验证。'],
 ['headphones','我有一个产品，想让它更容易被理解','把产品特点组织成清楚的视觉提案。','产品介绍图 / 包装概念','产品实拍、核心特点、已核实参数、目标受众。','为主体与信息分配层级，选择网点表达、标题和信息网格。','用于讨论的产品介绍主视觉或包装效果方向。','电商上架还需真实产品图、逐字准确参数、平台尺寸与品牌审核；不能用生成图证明实物性能。','适合风格化表达，不是精确工业建模或真实商品摄影。'],
 ['merchandise','我想给社群做一套周边','让布袋、卡片和衣服看起来属于同一个系列。','周边效果提案 / 视觉母版','社群主题、已有标识与配色、物料清单、预算和尺寸。','建立共同的主体、色彩与文字关系，探索它在不同载体上的表现。','一组用于选方向的物料效果图，以及共用视觉配方。','再做各载体独立排版、尺寸和材质适配、供应商文件与打样；批量生成管理需扩展。','作者有跨载体示例；稳定批量产出不是现成工具功能。'],
 ['night-market','我想办一场让人记住的活动','从活动主题，走到一套可发布的宣传材料。','活动主视觉 / 海报方向','活动目的、人群、准确名称与日期地点、发布渠道。','提炼一个有记忆点的视觉主题，把主题表达与事实信息分层。','可评审的活动主视觉；确认后延展为海报、邀请卡和分享配图。','事实文字独立核对与排版，各渠道重新构图；发布与活动报名系统不由此库提供。','海报场景有作者案例；我们已实测读书会概念图。'],
 ['chair','我有一批研究内容，想做成一本刊物','把内容组织成有统一视觉的阅读产品。','封面 / 章节视觉 / 刊物设计方向','目录、章节摘要、准确标题、阅读对象与版面规格。','为内容提炼视觉隐喻，建立封面与章节的构图和节奏。','封面和章节视觉素材，配合现有正文形成刊物设计方案。','完整书刊仍需编辑校对、长文排版、页码目录、版权与 PDF 导出；这些不是图像 Skill 的完整能力。','作者有 Zine 示例；本项目实测了研究封面与阅读专题。'],
 ['night-photography','我有照片或经历，想做成纪念作品','让原始素材变成有表达的视觉记录。','旅行札记 / 纪念卡 / 照片册视觉','有权使用的照片、故事、想保留的人物与地标、准确短句。','按照片主体重新裁切、处理网点和配色，把记录转成编辑视觉。','适合放入纪念卡、照片册或专题页面的风格化图片。','核对人物身份和场景特征，补齐相册排版、印刷尺寸与成品制作。','规范支持照片输入；本项目尚未验证照片保真。']
];
export function renderGoals(){return `<section id="user-goals" class="goal-section"><div class="wrap section"><div class="section-head"><div><div class="eyebrow">FROM AN IDEA TO A DELIVERABLE</div><h2>你有一个想法，<br>它能帮你推进到哪一步？</h2></div><p>从产品、品牌、活动与内容出发。<br>先看目标，再看需要哪些能力。</p></div><div class="goal-grid">${goals.map(([id,idea,sub,deliver,input,skill,result,next,status],i)=>{const c=cases.find(c=>c.id===id);return `<article class="goal-card"><a href="${c.source}" class="goal-image" target="_blank" rel="noopener noreferrer"><img src="${c.src}" alt="相关作者效果案例：${c.title}" loading="lazy" referrerpolicy="no-referrer"><span>作者案例：${c.title} ↗</span></a><div class="goal-content"><span class="eyebrow">需求 ${String(i+1).padStart(2,'0')}</span><h3>“${idea}”</h3><p class="goal-sub">${sub}</p><p class="goal-deliver">目标成果 → <b>${deliver}</b></p><ol><li><b>用户提供</b><p>${input}</p></li><li><b>Skill 帮忙设计</b><p>${skill}</p></li><li><b>先得到的成果</b><p>${result}</p></li><li><b>走到最终产品</b><p>${next}</p></li></ol><p class="goal-status">${status}</p></div></article>`;}).join('')}</div><div class="goal-summary"><b>这个库的价值：把想法推进为可讨论、可选择的视觉方案。</b><p>它可以参与“需求 → 视觉方向 → 生成效果图 → 审核调整”的过程。最终可发布文件、可生产包装或可售卖商品，还需要准确排版、工程与生产工具配合。图像生成由宿主模型执行；效果图不等于已制造的产品。</p></div><a class="text-link" href="#use-cases">继续拆解：实现这些目标需要哪些具体视觉能力 ↓</a></div></section>`;}
export function goalsMarkdown(){return '# 从用户想法到最终成果\n\nmono-color 帮助把需求转成可讨论的视觉方案；不是从想法直接交付实物产品的全流程平台。以下为基于规范与作者案例整理的应用路径，不是全部实测成功的交付承诺。\n\n'+goals.map(([id,idea,sub,deliver,input,skill,result,next,status])=>`## ${idea}\n\n目标：${deliver}。${sub}\n\n1. 用户提供：${input}\n2. Skill 参与：${skill}\n3. 先得到：${result}\n4. 最终落地：${next}\n\n验证范围：${status}\n`).join('\n');}
