import {cases} from './cases.mjs';
export const uses=[
 {title:'无文字主视觉 / 文章插图',case:'teapot',status:'规范支持 · 本场景待实测',input:'文章摘要、核心情绪、一个物件或动作。',output:'主体与网点质感为主的插图，标题留给网页或文档排版。',ours:'研究文章引图、章节过渡图、阅读笔记插图。',boundary:'表达主题与气氛，不能替代准确的知识图解。',prompt:'用 mono-color 为“慢下来理解一个问题”制作无文字插图，以一只手打开笔记本为主体，绿色单墨、可见网点、大量留白。不要字母、数字、标志或装饰文字。交付图片、提示词和配方。'},
 {title:'照片转译 / 肖像与街景',case:'night-photography',status:'规范支持 · 本项目未验证保真',input:'有权使用的人像、旅行或街景照片，以及必须保留的识别特征。',output:'保留主体特征、重新裁切与排布的单双色编辑图像。',ours:'访谈人物视觉、旅行札记、城市观察专题。',boundary:'需提供真实输入照片；逐项检查身份、表情和地标，不保证像素保真。',prompt:'把我提供的街景照片转成钴蓝单墨编辑插图，保留建筑轮廓与道路关系，重新裁切并使用机械网点，不添加文字、人物或不存在的地标。输出前检查主体是否仍可辨认。'},
 {title:'物件观察 / 自然主题图版',case:'zebra',status:'作者有相关视觉案例',input:'植物、动物或日常物件照片；需要突出的形状、纹理和细节。',output:'带强裁切、尺度反差或少量编号的视觉观察图。',ours:'素材研究卡、产品观察笔记、自然主题章节。',boundary:'适合视觉观察，不是科学插图；结构与标注需要专业核对。',prompt:'用 mono-color 为一片蕨叶制作无标题观察图，保留叶片形状与叶脉，用植物绿单墨网点，突出一个巨大局部并留出安静区域。不要虚构物种名称或科学标注。'},
 {title:'包装贴纸 / 礼盒概念',case:'sardines',status:'作者有包装效果案例',input:'产品照片、包装尺寸、已有品牌规范与已确认的产品信息。',output:'盒面、套纸或标签的视觉概念，帮助比较设计方向。',ours:'阅读礼包、研究资料套装、活动纪念品的概念提案。',boundary:'示例图不是刀模、可编辑色版或印厂文件；尺寸、文字与工艺另行制作。',prompt:'为阅读资料套纸制作双色平面视觉概念，主墨钴蓝、辅墨陶土橙，主体是纸页的巨大裁切。只使用我提供的文字；未提供的信息留空。交付平面图，不生成产品参数或印刷合格声明。'},
 {title:'品牌物料 / 跨载体系列',case:'merchandise',status:'作者有系列效果案例',input:'共享主题、品牌色、标识使用规范，以及每件物料的尺寸。',output:'具有共同视觉元素的布袋、卡片、贴纸等方向提案。',ours:'研究社群周边、分享活动整套物料。',boundary:'单张系列效果可参考；批量任务管理、精确标识与稳定一致性需要额外实现。',prompt:'为研究社群设计一张双色视觉母版，钴蓝主体、陶土橙仅作圈注，用打开的书表达知识共享，不生成 logo。给出它适配明信片与布袋时的重排建议，不把建议声称为已完成的生产文件。'},
 {title:'刊物内页 / 章节与扉页',case:'chair',status:'规范支持 · 作者有 Zine 案例',input:'章节主题、准确短标题、版心尺寸与已有文字排版。',output:'扉页、章节图、独立刊物视觉页，控制内容之间的阅读节奏。',ours:'长文翻译、研究报告、专题阅读合集的章节视觉。',boundary:'长正文、页码和跨页连续性应由文档排版系统完成。',prompt:'为“观察日常”章节制作一张无正文扉页图，以一把椅子的大小对比建立构图，植物绿与酒红双色，留出标题区域，不添加字。交付图片、提示词与配方。'},
 {title:'播客 / 音频节目视觉',case:'radio',status:'规范支持 · 作者有聆听主题案例',input:'单集主题、主持人照片或声音相关物件，以及准确单集标题。',output:'播客封面、音频专栏插图或单集分享图。',ours:'研究访谈、读书音频、技术分享录音的视觉入口。',boundary:'它不生成音频；缩略图可读性与各平台尺寸需要单独检查。',prompt:'用 mono-color 为“听见日常”制作一张方形音频专题插图，以收音机与耳机为物件家族，钴蓝与黑墨，保留一个强焦点，不添加文字。确保缩小后主体仍能辨认。'},
 {title:'社交内容 / 多渠道视觉',case:'sunscreen',status:'场景支持 · 多尺寸自动化待扩展',input:'同一主题的摘要、渠道尺寸、准确短文案与共用配方。',output:'公众号配图、社交封面、邀请卡等不同用途的单张视觉。',ours:'同一份研究的文章首图、分享卡片与活动预告。',boundary:'需按画幅重新构图；网页没有一键批量出图或自动适配功能。',prompt:'沿用研究封面的配色与视觉主体，制作一张横向分享配图。按新画幅重新安排主体和留白，不拉伸旧图，不添加未经确认的信息。记录本次配方与竖版的差异。'}
];
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
export function renderUses(){return `<section id="use-cases" class="wrap section"><div class="section-head"><div><div class="eyebrow">BEYOND TEXT POSTERS / 8 APPLICATIONS</div><h2>文字只是其中一种输入。</h2></div><p>也可以从照片、物件与内容主题出发，<br>制作少文字、无文字或跨载体的视觉。</p></div><div class="use-grid">${uses.map((u,i)=>{const c=cases.find(c=>c.id===u.case);return `<article class="use-card"><a href="${c.source}" target="_blank" rel="noopener noreferrer" class="use-reference"><img src="${c.src}" alt="相关作者案例：${c.title}" loading="lazy" referrerpolicy="no-referrer"><span>相关作者案例 · ${c.title} ↗</span></a><div class="use-content"><span class="eyebrow">${String(i+1).padStart(2,'0')} / ${u.status}</span><h3>${u.title}</h3><dl><dt>输入</dt><dd>${u.input}</dd><dt>产出</dt><dd>${u.output}</dd><dt>我们可用</dt><dd>${u.ours}</dd></dl><p class="use-boundary">${u.boundary}</p><details><summary>展开试用请求 <span>待执行</span></summary><div><p>${esc(u.prompt)}</p></div></details></div></article>`;}).join('')}</div><p class="small-note">配图是相关上游作者案例，帮助理解视觉方向，不代表旁边的请求已经执行；请求为本项目编写。照片输入、无文字输出和批量一致性仍需分别实测。作者图片从原站加载，© 2026 Yan Liu。</p><p class="text-link">建议先做：研究文章无文字插图 → 章节视觉 → 分享物料；有真实照片后，再验证照片转译。</p></section>`;}
export function usesMarkdown(){return '# 不止文字海报：使用场景\n\n依据固定版本的 Skill 与作者案例整理。以下请求为待执行示例，不能算作新实测结果。\n\n'+uses.map(u=>`## ${u.title}\n\n${u.status}\n\n- 输入：${u.input}\n- 产出：${u.output}\n- 我们可用：${u.ours}\n- 边界：${u.boundary}\n\n试用请求（未执行）：\n\n> ${u.prompt}\n`).join('\n');}
