import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {styles,categories,routes,upstream,commit,date} from './data.mjs';
import {demos,renderDemos} from './demos.mjs';
import {createHash} from 'node:crypto';
import './overview.mjs';
const dir=path.dirname(fileURLToPath(import.meta.url));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const ext=(url,text,cls='')=>`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${text} <span aria-hidden="true">↗</span></a>`;
const source=(file,label)=>ext(`${upstream}/blob/${commit}/${file}`,label);
const demoHtml=renderDemos({upstream,commit,esc,ext});
const generatedFiles=JSON.parse(fs.readFileSync(path.join(dir,'../notes/generated-assets.json'),'utf8').replace(/^\uFEFF/,''));
for(const d of demos)for(const name of [d.input,d.output].filter(Boolean)){
  const record=generatedFiles.find(f=>f.file===name);
  const file=path.join(dir,'../assets/generated',name);
  if(!record||!fs.existsSync(file)||createHash('sha256').update(fs.readFileSync(file)).digest('hex')!==record.sha256)throw new Error('生成图缺失或与实验记录不一致：'+name);
}
if(styles.length!==28||new Set(styles.map(s=>s.slug)).size!==28)throw new Error('风格目录数量或调用名重复');
for(const route of routes)if(!styles.some(s=>s.slug===route.slug)||route.steps.length!==5)throw new Error('流程数据不完整');
const cards=styles.map(s=>`<article class="style-card" data-slug="${s.slug}" data-category="${s.category}" data-search="${esc([s.name,s.slug,s.category,s.input,s.scene,s.visual].join(' '))}"><button class="image-button" type="button" data-detail="${s.slug}" aria-label="了解${s.name}"><img src="${s.image}" alt="${s.name}：上游公开风格展示图，非本项目生成" loading="lazy" width="480" height="480"><span class="image-fallback" hidden>图片暂未载入<br><small>仍可查看规则与上游来源</small></span><span class="image-label">上游展示图</span><span class="image-open" aria-hidden="true">↗</span></button><div class="card-meta"><span>${s.category}</span><span>${String(s.id).padStart(2,'0')}</span></div><h3><button type="button" data-detail="${s.slug}">${s.name}</button></h3><p>${s.visual}</p><div class="card-bottom"><span>${s.method}</span><button type="button" data-detail="${s.slug}" aria-label="查看${s.name}的适用场景">了解这款 <span aria-hidden="true">↗</span></button></div></article>`).join('');
const heroSlugs=['electric-blue-halftone-poster','retro-table-print','textile-toy-portrait','minimal-pet-doodle'];
const hero=heroSlugs.map((slug,i)=>{const s=styles.find(x=>x.slug===slug);return `<a class="hero-tile tile-${i}" href="#catalog" aria-label="浏览${s.name}等风格"><img src="${s.image}" alt="上游${s.name}展示图" width="420" height="420" fetchpriority="${i===0?'high':'auto'}"><span>${s.name}<b>↗</b></span></a>`}).join('');
const refs=[['README.md','28 款风格与适用输入','名称、调用名、风格数量与使用方式'],['skills/electric-blue-halftone-poster/SKILL.md','最简路线：文字规则如何驱动生图','输入约定、工具调用与交付规则'],['skills/wibi-frame/references/frame.md','复杂路线：先选局部，再组织版式','参考图、构图卡和两步生成'],['skills/wibi-frame/references/checks.md','生成后的验收与重做边界','视觉自检、尺寸和分层收尾'],['skills/retro-table-print/scripts/vintage_finish.py','脚本如何完成印刷质感','图像后处理，不是独立生图模型'],['skills/underground-audition/SKILL.md','多视角生成的已知限制','其他角度属于模型推演，可能漂移'],['skills/office-animals/scripts/draw_brief.py','文字创作的组合机制','动物、场景、情绪与文案'],['LICENSE','原项目使用许可','个人非商业使用与商业授权要求']];
const html=`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f6f5f0"><meta name="description" content="以 28 款真实风格展示和三条交互流程，理解 wibi-style 的能力、使用场景和 Skill 如何驱动图像生成。"><title>wibi-style｜把风格变成可执行的配方 · 研究 003</title><link rel="stylesheet" href="./styles.css"><script src="./app.js" defer></script></head>
<body><a class="skip" href="#main">跳到主要内容</a><header class="site-header"><a class="brand" href="../../"><span class="brand-mark" aria-hidden="true">研</span><span>项目研究集<small>OPEN RESEARCH</small></span></a><nav aria-label="页面导航"><a href="#generated-demo">实际效果</a><a href="#catalog">风格图鉴</a><a href="#flow">如何驱动</a><a href="#findings">研究总结</a></nav>${ext(upstream,'上游仓库','repo-link')}</header>
<main id="main"><section class="hero" id="overview"><div class="hero-copy"><div class="eyebrow"><span class="dot"></span> RESEARCH 003 <span class="eyebrow-divider">/</span> WIBI-STYLE</div><h1>把风格，<br>变成可执行的<span class="accent-word">配方<span class="asterisk" aria-hidden="true">✳</span></span>。</h1><p class="hero-lead">选一种风格，给一张照片。<br>现在，用三组实际生成结果看它如何起作用。</p><div class="hero-actions"><a class="button primary" href="#generated-demo">看本次生成效果 <span>↗</span></a><a class="button secondary" href="#catalog">探索 28 款风格 <span>↓</span></a></div><p class="hero-footnote">本次真实生图实验 + 上游风格图鉴 · 网页展示已生成的结果</p></div><div class="hero-art"><div class="art-caption"><span>ONE LIBRARY, MANY VISUAL LANGUAGES</span><span>01—28</span></div><div class="hero-mosaic">${hero}</div><p class="image-credit">上游真实展示图 · Visual Skill by @威比 Hunter Wei.</p></div></section>
<div class="facts-strip"><div><strong>28<span>款</span></strong><p>可独立选择的视觉风格</p></div><div><strong>3<span>条</span></strong><p>代表性工作流拆解</p></div><div><strong>1<span>个核心</span></strong><p>把审美经验写成执行规则</p></div><div class="fact-note"><span class="dot"></span><p>研究版本 <code>${commit.slice(0,7)}</code><br>核对日期 ${date}</p></div></div>
${demoHtml}
<div class="boundary-box"><h3>28 款风格，一图看全。</h3><p>完整列出蜡笔手绘、牛马宇宙等全部风格与上游效果。<a href="./style-atlas-28.png" target="_blank" rel="noopener noreferrer">打开总览大图 ↗</a> · <a href="./style-atlas-28.png" download>下载 PNG ↓</a> · <a href="./overview.html">浏览完整排版 ↗</a></p></div>
<section class="mental-model" aria-labelledby="model-title"><div><span class="eyebrow">先用一句话理解</span><h2 id="model-title">它是一套制作配方。<br>AI 按配方，调用工具。</h2></div><div class="role-grid"><article><span class="role-number">01 / SKILL</span><h3>说明书</h3><p>规定构图、颜色、素材使用和验收标准。</p></article><article><span class="role-number">02 / AGENT</span><h3>执行者</h3><p>看懂照片，读取规则，组织本次生成任务。</p></article><article><span class="role-number">03 / IMAGE MODEL</span><h3>绘图工具</h3><p>接收照片与指令，实际生成或编辑图片。</p></article></div></section>
<section id="catalog" class="section"><div class="section-heading"><div><div class="eyebrow">01 / STYLE ATLAS</div><h2>你手上的照片，<br class="mobile-break">可以变成什么？</h2></div><p>按题材探索，点击卡片了解输入、用途与边界。<br>展示图来自上游，不代表我们实测的成功率。</p></div><div class="catalog-tools"><div class="filter-list" role="group" aria-label="按题材筛选">${categories.map((c,i)=>`<button type="button" data-filter="${c}" aria-pressed="${i===0}" class="filter ${i===0?'active':''}">${c}</button>`).join('')}</div><label class="search-box"><span aria-hidden="true">⌕</span><input id="style-search" type="search" placeholder="搜索风格、用途…" aria-label="搜索风格、用途或调用名"></label></div><div class="catalog-status"><p id="style-count" aria-live="polite">全部风格 · 28 款</p><span>分类为本研究归纳，部分风格适用多种题材</span></div><div class="style-grid">${cards}</div><div id="empty-state" class="empty-state" hidden><h3>没有找到匹配的风格</h3><p>试试“头像”“餐桌”或“宠物”，也可以清除筛选。</p><button class="button secondary" id="reset-filters" type="button">显示全部风格</button></div><p class="catalog-note">图片从上游固定版本远程载入；网络不可用时，文字图鉴与流程仍可使用。${source('README.md','对照上游完整目录')}</p></section>
<section id="flow" class="flow-section section"><div class="section-heading"><div><div class="eyebrow">02 / HOW IT WORKS</div><h2>从选择风格，<br>到交付一张图片。</h2></div><p>切换三条路线，逐步看谁在做什么。<br>这是流程讲解，不会执行生图或消耗生成次数。</p></div><div class="route-tabs" role="group" aria-label="选择代表性工作流">${routes.map((r,i)=>`<button type="button" data-route="${i}" class="${i===0?'active':''}" aria-pressed="${i===0}"><span>0${i+1}</span>${r.name}</button>`).join('')}</div><div class="flow-workspace"><div class="step-list" role="group" aria-label="选择生成步骤">${['提供输入','读取配方','AI 组织任务','模型与工具','检查与交付'].map((s,i)=>`<button type="button" data-step="${i}" aria-pressed="${i===0}" aria-controls="flow-panel" class="${i===0?'active':''}"><span>0${i+1}</span>${s}<b aria-hidden="true">→</b></button>`).join('')}</div><article class="flow-panel" id="flow-panel" aria-live="polite"><div class="panel-top"><span id="route-label">${routes[0].label}</span><span id="step-progress">01 / 05</span></div><h3 id="step-title">${routes[0].steps[0][0]}</h3><p id="step-description">${routes[0].steps[0][1]}</p><div class="output-box"><span>这一步得到</span><strong id="step-output">${routes[0].steps[0][2]}</strong></div><p class="step-note" id="step-note">${routes[0].steps[0][3]}</p><div class="panel-bottom"><a id="route-source" href="${styles[0].source}" target="_blank" rel="noopener noreferrer">查看对应 Skill ↗</a><button type="button" id="next-step">下一步 <span>→</span></button></div></article><aside class="recipe-aside"><span class="eyebrow">一款风格包里有什么？</span><div><code>SKILL.md</code><p>入口、触发条件与执行顺序</p></div><div><code>references/</code><p>风格规则与检查清单</p></div><div><code>assets/ · 可选</code><p>参考图片或构图卡</p></div><div><code>scripts/ · 按需</code><p>排版、后处理与更新检查</p></div><div><code>manifest.json</code><p>版本、来源与许可信息</p></div></aside></div><div class="flow-takeaway"><span>关键区别</span><p>作者提前整理好风格规则。用户选择后，Agent 在本次任务里读取并执行；这个仓库本身不训练模型，也不自动上网学习新风格。</p></div></section>
<section id="scenarios" class="section"><div class="section-heading"><div><div class="eyebrow">03 / USE CASES</div><h2>从一个具体用途开始。</h2></div><p>更适合创意表达和风格探索。<br>对真实细节的要求越高，越需要人工复核。</p></div><div class="scenario-grid">${[['01','一张自拍','做一张有个性的头像','漫画、网点、蜡笔或玩偶风格，围绕人物特征进行再创作。','人像'],['02','一张生活照','把日常做成视觉记录','餐桌、家居、街景和自然风景，可以获得统一的视觉气质。','场景'],['03','一只毛孩子','留下一张宠物纪念图','抓住动作、视线和毛色，用极简线条或装饰语言表达。','宠物'],['04','一个有趣想法','生成办公室主题海报','提供动物、场景与情绪，让组合规则组织创意和中文标题。','文字创作']].map(([n,input,title,body,cat])=>`<article><span class="scenario-number">${n}</span><small>${input}</small><h3>${title}</h3><p>${body}</p><button type="button" data-scenario="${cat}">看看适合的风格 ↗</button></article>`).join('')}</div><div class="boundary-box"><h3>使用前，明确交付目标。</h3><p>多视角人像包含模型推演；拼豆效果图不是生产图纸；生成图片不等于可编辑矢量源文件。人物身份、精确商品外观和文字排版需要额外验证。${source('skills/underground-audition/SKILL.md','上游已知限制')}</p></div></section>
<section id="findings" class="section findings-section"><div class="section-heading"><div><div class="eyebrow">04 / RESEARCH NOTES</div><h2>值得复用的，<br>是把经验写成流程的方法。</h2></div><span class="pill">以下为本研究判断</span></div><div class="finding-grid"><article><span>对我们 / 01</span><h3>让研究输出有统一规范</h3><p>将来源核对、能力分析、实验记录与结论边界组织成自己的研究 Skill，让每个子项目都能按同一套质量要求交付。</p></article><article><span>对我们 / 02</span><h3>建立原创视觉配方</h3><p>为研究封面与概念插画制定配色和构图规范。架构图、数据图和真实截图仍采用可核对、可编辑的方式制作。</p></article><article><span>对我们 / 03</span><h3>用小实验验证真实增益</h3><p>对同一批照片比较普通提示词与完整 Skill，记录身份保留、构图遵循、风格一致性、耗时和重做次数。</p></article></div><div class="extension"><div><span class="eyebrow">NEXT / 可扩展方向</span><h3>先提高可验证性，<br>再增加风格数量。</h3></div><ol><li><span>优先</span><div><b>固定样本与对照评测</b><p>验证配方究竟提升了什么，不用目录数量代替效果。</p></div></li><li><span>优先</span><div><b>程序检查与精确排版</b><p>对尺寸、格式、色值和版式做确定性处理。</p></div></li><li><span>后续</span><div><b>参数、模型适配与批量记录</b><p>逐步加入比例、配色、模型能力适配和版本追溯。</p></div></li></ol></div></section>
<section id="evidence" class="section evidence-section"><div class="section-heading"><div><div class="eyebrow">05 / SOURCES & BOUNDARIES</div><h2>事实有出处，判断有边界。</h2></div><span class="pill">固定版本 · ${commit.slice(0,7)}</span></div><div class="evidence-summary"><div><b>本轮已完成</b><p>源码核对、3 个实际生成场景、5 个生成文件与网页交互展示。</p></div><div><b>本轮未验证</b><p>总体成功率、跨模型一致性、完整官方流程和生成成本。</p></div><div><b>许可边界</b><p>上游原创规则与构图模板限个人非商业使用；商业用途需作者事先书面许可。</p></div></div><ol class="references">${refs.map(([file,title,desc],i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><div>${source(file,title)}<p>${desc}</p></div></li>`).join('')}</ol><div class="author-note"><b>上游作者：@威比 Hunter Wei. · 抖音、小红书同名</b><p>本页是独立研究展示，不是官方产品。风格名称与远程展示图来自上游；说明、交互与研究结论由本研究整理。未复制运行参考图、案例原片或完整风格包。${source('LICENSE','阅读原许可')} · <a href="./research.md">研究记录</a> · <a href="./upstream-LICENSE.txt">上游许可存档</a></p></div></section>
<footer><a class="brand footer-brand" href="../../"><span class="brand-mark" aria-hidden="true">研</span><span>项目研究集 <small>003 / WIBI-STYLE</small></span></a><span>研究 ${date} · 从理解工具，到复用方法。</span><a href="#overview">返回顶部 ↑</a></footer></main>
<dialog id="style-dialog" aria-labelledby="detail-title"><button type="button" id="close-dialog" aria-label="关闭风格详情">×</button><div class="detail-layout"><div class="detail-image-wrap"><img id="detail-image" alt="" width="600" height="600"><p>上游风格展示图 · 非本项目生成</p></div><div class="detail-copy"><span id="detail-category" class="eyebrow"></span><h2 id="detail-title"></h2><p id="detail-description"></p><dl><dt>你需要提供</dt><dd id="detail-input"></dd><dt>适合的用途</dt><dd id="detail-scene"></dd><dt>视觉语言</dt><dd id="detail-visual"></dd></dl><label for="detail-command">安装后，在具备生图能力的环境中调用</label><textarea id="detail-command" rows="2" readonly></textarea><div class="detail-actions"><button class="button primary" type="button" id="copy-command">复制调用示例</button><a id="detail-source" class="button secondary" href="${upstream}" target="_blank" rel="noopener noreferrer">查看上游 Skill ↗</a></div><p id="copy-status" class="copy-status" role="status"></p><small class="detail-caveat">这里只展示能力与用法；本网页没有安装或执行 Skill。</small></div></div></dialog>
<script id="research-data" type="application/json">${JSON.stringify({styles,routes}).replaceAll('<','\\u003c')}</script><noscript><div class="noscript">JavaScript 未启用：可阅读全部风格与研究结论；筛选和流程切换需要 JavaScript。各款细节也可从上游完整目录查看。</div></noscript></body></html>`;
const dist=path.join(dir,'dist');fs.mkdirSync(dist,{recursive:true});
fs.writeFileSync(path.join(dist,'index.html'),html);
for(const file of ['styles.css','app.js'])fs.copyFileSync(path.join(dir,file),path.join(dist,file));
fs.copyFileSync(path.join(dir,'../notes/research.md'),path.join(dist,'research.md'));
fs.copyFileSync(path.join(dir,'../notes/upstream-LICENSE.txt'),path.join(dist,'upstream-LICENSE.txt'));
fs.copyFileSync(path.join(dir,'../assets/style-atlas-28.png'),path.join(dist,'style-atlas-28.png'));
fs.mkdirSync(path.join(dist,'generated'),{recursive:true});
for(const file of generatedFiles)fs.copyFileSync(path.join(dir,'../assets/generated',file.file),path.join(dist,'generated',file.file));
for(const name of ['generation-experiments.md','generation-prompts.md','generation-prompts.json','generated-assets.json'])fs.copyFileSync(path.join(dir,'../notes',name),path.join(dist,name));
console.log('已构建 wibi-style 研究网页：28 款风格 / 3 条流程 / 3 个实际生成场景，5 个文件散列一致。');
