export const demos=[
  {id:'portrait',name:'人像 → 电蓝海报',slug:'electric-blue-halftone-poster',mode:'图像编辑',input:'portrait-input-v1.png',output:'portrait-output-v1.png',ratio:'1 / 1',size:'1254 × 1254',title:'同一个人物，换一种视觉语言。',brief:'把这张肖像做成电蓝网点海报，保留眼镜、发型、表情和耳饰。',rules:['照片决定人物特征','文字规则决定构图与色彩','生图模型重绘黑白网点'],kept:'短发、圆框眼镜、微笑和耳环仍可辨认；黑白主体、电蓝背景及六颗红黄星星已呈现。',limit:'网点比目标偏细，头发外缘有白色细边；不能视为全部风格检查项通过。',sourceNote:'输入为本次 AI 生成的虚构成年人，并非真实用户照片。',inputAlt:'本次 AI 生成的虚构人物输入：短发、圆框眼镜、耳环与绿色毛衣',outputAlt:'本次实际编辑结果：同一人物的黑白网点大头、电蓝背景与六颗红黄星星',callNote:'1 次生成输入 + 1 次编辑；保留首轮结果'},
  {id:'table',name:'餐桌 → 复古杂志',slug:'retro-table-print',mode:'图像编辑',input:'table-input-v1.png',output:'table-output-v1.png',ratio:'3 / 4',size:'1086 × 1448',title:'从餐桌随拍，到杂志式构图。',brief:'保留同一盘番茄意面、三片罗勒、蓝边餐盘与水杯，重做红底复古构图。',rules:['锁定食物与器皿识别特征','盘子偏心出框，左上留白','模型表现复古印刷质感'],kept:'三片罗勒、蓝边餐盘、水杯与叉子保留；餐盘移到右下并出框，左上出现连续红色留白。',limit:'部分芝士和面条细节被重绘，背景颗粒较明显；没有执行上游 vintage_finish.py，不能代表完整官方流水线。',sourceNote:'输入为本次 AI 生成的餐桌样图；输出实际以该文件作为编辑输入。',inputAlt:'本次生成的餐桌输入：木桌上的番茄意面、三片罗勒、蓝边餐盘、水杯和叉子',outputAlt:'本次实际编辑结果：偏心出框的意面餐盘、左上红底留白和复古颗粒',callNote:'1 次生成输入 + 1 次编辑；无另行后处理'},
  {id:'office',name:'文字 → 水豚开会',slug:'office-animals',mode:'文字生图',input:null,output:'office-output-v1.png',ratio:'3 / 4',size:'1086 × 1448',title:'一句需求，组织成一张海报。',brief:'一只水豚在办公室开会，情绪稳定。做成中文 Y2K 海报，标题为“今天也很稳定”。',rules:['文字指定动物、场景和情绪','红色主标题与蓝色宋体边注','图像模型同时绘制场景与文字'],kept:'水豚、会议桌和电脑组成可读场景；主标题及四组中文边注可辨认，红蓝层次清楚。',limit:'红色剪贴描边连带包住了部分椅子，纸边旧化比要求更明显；中文可读性只针对这个样本进行目视核对。',sourceNote:'这条路线没有输入图片，动物、场景与文字均由本次模型生成。',inputAlt:'',outputAlt:'本次生成的水豚开会海报，红色标题今天也很稳定、蓝色边注与真实感水豚',callNote:'1 次文字生图；未调用官方随机脚本'},
];

export function renderDemos({upstream,commit,esc,ext}){
  const image=(file,alt)=>`<a class="demo-image-link" href="./generated/${file}" target="_blank" rel="noopener noreferrer" aria-label="打开${esc(alt)}原图"><img src="./generated/${file}" alt="${esc(alt)}" loading="lazy"><span aria-hidden="true">打开原图 ↗</span></a>`;
  return `<section id="generated-demo" class="section generated-section"><div class="section-heading"><div><div class="eyebrow"><span class="dot"></span> MODEL OUTPUTS / 本次实际生成</div><h2>选一个场景，<br class="mobile-break">直接看效果。</h2></div><p>2 组图像输入与输出 + 1 张文字海报。<br>以下都是本次内置生图工具的实际结果。</p></div><div class="demo-tabs" role="group" aria-label="选择实际生成场景">${demos.map((d,i)=>`<button type="button" data-demo="${d.id}" class="${i===0?'active':''}" aria-pressed="${i===0}" aria-controls="demo-${d.id}"><img src="./generated/${d.output}" alt="" width="48" height="48" loading="lazy"><span><b>${d.name}</b><small>${d.mode} · 已生成</small></span><span aria-hidden="true">↗</span></button>`).join('')}</div><p id="demo-selection" class="demo-selection" aria-live="polite">正在查看：${demos[0].name}</p>${demos.map((d,i)=>`<article class="demo-case" id="demo-${d.id}" ${i?'hidden':''} aria-labelledby="demo-title-${d.id}"><div class="demo-brief"><span class="eyebrow">CASE 0${i+1} / ${d.mode}</span><h3 id="demo-title-${d.id}">${d.title}</h3><span class="demo-label">本次需求</span><p class="demo-request">${d.brief}</p><ol>${d.rules.map(r=>`<li>${r}</li>`).join('')}</ol><p class="demo-source-note">${d.sourceNote}</p><div class="demo-links">${ext(`${upstream}/tree/${commit}/skills/${d.slug}`,'对应上游风格')}<a href="./generation-prompts.md">本次实际提示词 ↗</a></div></div><div class="demo-images" style="--demo-ratio:${d.ratio}">${d.input?`<figure><figcaption><span>INPUT / 输入素材</span><b>AI 生成样图</b></figcaption>${image(d.input,d.inputAlt)}</figure>`:`<figure class="text-input-figure"><figcaption><span>INPUT / 文字需求</span><b>无参考图片</b></figcaption><div class="text-input-card"><span class="eyebrow">给模型的场景设定</span><span class="quote-mark" aria-hidden="true">“</span><p>一只水豚<br>在办公室开会，<br><strong>情绪稳定。</strong></p><dl><dt>主标题</dt><dd>今天也很稳定</dd><dt>蓝色边注</dt><dd>情绪稳定 / 准时下班<br>会议观察 / 保持平静</dd><dt>视觉要求</dt><dd>Y2K 中文杂志、红字蓝注、<br>自然动物身体与机顶直闪</dd></dl><span class="text-input-foot">此卡展示本次需求，不是生成图片。</span></div></figure>`}<figure><figcaption><span>OUTPUT / 实际输出</span><b>本次模型生成</b></figcaption>${image(d.output,d.outputAlt)}</figure></div><div class="demo-observation"><div><span>这次做到了什么</span><p>${d.kept}</p></div><div><span>仍然存在的偏差</span><p>${d.limit}</p></div></div><div class="demo-case-footer"><span>${d.callNote}</span><a href="./generated/${d.output}" download="${d.output}">下载结果 PNG · ${d.size} ↓</a></div></article>`).join('')}<div class="demo-method-note"><b>演示方法</b><p>参考 wibi-style 公开规则，由本研究编写场景提示词并调用内置 image_gen；未安装或完整执行官方 Skill，未使用其随包参考图或后处理脚本。共 5 次提交、5 个文件，无重试。模型具体版本未由工具返回。这 3 个样本展示能力与偏差，不构成成功率或成本评测。</p><div><a href="./generation-experiments.md">完整实验记录 ↗</a><a href="./generation-prompts.md">完整提示词集 ↗</a><a href="./generated-assets.json">文件尺寸与 SHA-256 ↗</a></div></div></section>`;
}
